### PR TITLE
More small fixes

### PR DESCRIPTION
**Pull request by KJeff01**
I made some potential fixes for the super pulse laser cyborg template and the defense structure building for nullbots. 

Also I suspect that ticket 4521 is caused when nullbot tries to produce combat engineers. I am not sure what causes it though.

### CODE REVIEW

**Comment by haoNoQ** [comment]
The catch with pulse cyborgs is great. Not sure if engineers have the same problem, i'm sure i double-checked the template.

The second change seems correct, but i do not understand the commit message. Consequences of this change include building laser satellites before repair facilities when available (not sure if correct), better sensor towers before outdated sensor towers (great), and better artillery before worse artillery (great, but not sure if i've ever seen this broken), and that's it.

**Comment by KJeff01** [comment]
Defense building would never build the last defense structure even if the nullbot researched it. Example: Seraph missile battery would only be built despite having archangel pits and so on.

The engineer template looks correct despite producing half of the engineer.

**Comment by haoNoQ** [comment]
> Defense building would never build the last defense structure even if the nullbot researched it. 

But you're not changing this. You're only reversing the priority of structures. Eg. if you wrote "MRA emplacement would only be built despite having archangel pits" that'd sound correct, however there's nothing special about last vs. one-before-last. Could you check it one more time?

**Comment by KJeff01** [comment]
I tested without the change and this time it worked like it should. I guess I just saw some matches where it did not build the last item.

**Comment by haoNoQ** [comment]
Merged the first commit, discarded the second commit, as per discussion.

**Pull request closed without merging**
